# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :beta do
    sync_code_signing(type: "appstore")    # see code signing guide for more information
    build_app(scheme: "App")
    upload_to_testflight
  end

 lane :frameit_screenshots do
    # It frames the screenshots in landscape right whenever the filename contains `landscape` word
    frameit(
      silver: true,
      path: "./fastlane/screenshots",
      force_orientation_block: proc do |filename|
        f = filename.downcase
        if f.include?("landscape")
          :landscape_right
        end
      end
    )
  end

end


